FORMAT: 1A
HOST: http://millipede.io

# Millipede API

Millipede is a simple API allowing consumers to create millipedes.

## Millipede Resource [/{?size,comment}]

### Create a Millipede [GET]

+ Parameters
    + size (optional, number) ... Size of the millipede
    + comment (optional, string) ... Header comment

+ Response 200 (text/plain)

        Hello World
        
            ╚⊙ ⊙╝
          ╚═(███)═╝
         ╚═(███)═╝
        ╚═(███)═╝
         ╚═(███)═╝
          ╚═(███)═╝
           ╚═(███)═╝
            ╚═(███)═╝
            ╚═(███)═╝
           ╚═(███)═╝
          ╚═(███)═╝
         ╚═(███)═╝
        ╚═(███)═╝
         ╚═(███)═╝
          ╚═(███)═╝
           ╚═(███)═╝
            ╚═(███)═╝
            ╚═(███)═╝
           ╚═(███)═╝
          ╚═(███)═╝
         ╚═(███)═╝
        ╚═(███)═╝
         ╚═(███)═╝
          ╚═(███)═╝
           ╚═(███)═╝
            ╚═(███)═╝
            ╚═(███)═╝
           ╚═(███)═╝
          ╚═(███)═╝
         ╚═(███)═╝
        ╚═(███)═╝
         ╚═(███)═╝
          ╚═(███)═╝
           ╚═(███)═╝
            ╚═(███)═╝
            ╚═(███)═╝
           ╚═(███)═╝
          ╚═(███)═╝
         ╚═(███)═╝
        ╚═(███)═╝
         ╚═(███)═╝
          ╚═(███)═╝
           ╚═(███)═╝
